import Head from 'next/head';
import LoginForm from '../components/authentication/LoginForm';
import RegistrationForm from '../components/authentication/RegistrationForm';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import WelcomeSection from '../components/homepage/WelcomeSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Beauty Asszisztens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <WelcomeSection />
        <Container>
          <Row>
          </Row>
          <Row>
            <Col lg={6}>
              <RegistrationForm />
            </Col>
            <Col lg={6}>
              <LoginForm />
            </Col>
          </Row>
        </Container>
      </section>
    </>
  )
}
