import Head from 'next/head';
import AuthenticationSection from '../components/homepage/AuthenticationSection';
import WelcomeSection from '../components/homepage/WelcomeSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Beauty Asszisztens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <WelcomeSection />
        <AuthenticationSection />
      </section>
    </>
  )
}
